owner: DHBern
repo: upptime_digitaleditions

sites:
  - name: Annemarie Schwarzenbach. Digitale Edition der Kleinen Formen und Briefe
    url: https://annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach DAV
    url: https://dav.annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 401
  - name: Arcipelago Ceresa
    url: https://arcipelago-ceresa.digitaleditions.ch/
    expectedStatusCodes:
      - 404
  - name: Arcipelago Ceresa IIIF presentation API
    url: https://iiif.arcipelago-ceresa.digitaleditions.ch/presentation/
    expectedStatusCodes:
      - 200
  - name: Brandans Meerfahrt
    url: https://brandans-meerfahrt.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Digital Editions – University of Bern
    url: https://digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek
    url: https://gossembrot.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek (Redirect to gossembrot.unibe.ch)
    url: https://gossembrot.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek (Redirect to gossembrot.unibe.ch)
    url: https://www.gossembrot.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek (Redirect to gossembrot.digitaleditions.ch)
    url: https://www.gossembrot.unibe.ch/
    expectedStatusCodes:
      - 200      
  - name: Parzival
    url: https://parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival (Redirect to parzival.unibe.ch)
    url: https://parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival (Redirect to parzival.unibe.ch)
    url: https://www.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival (Redirect to parzival.digitaleditions.ch)
    url: https://www.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival legacy
    url: https://parzdb.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival legacy (Redirect to parzdb.parzival.unibe.ch)
    url: https://www.parzdb.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival API
    url: https://data.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Rappoltstein
    url: https://rappoltstein.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Rappoltstein (Redirect to rappoltstein.parzival.unibe.ch)
    url: https://rappoltstein.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Rappoltstein (Redirect to rappoltstein.parzival.unibe.ch)
    url: https://www.rappoltstein.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Rappoltstein (Redirect to rappoltstein.parzival.digitaleditions.ch)
    url: https://www.rappoltstein.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cgm 19
    url: https://cgm19.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cgm 19 (Redirect to cgm19.parzival.unibe.ch)
    url: https://cgm19.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cgm 19 (Redirect to cgm19.parzival.unibe.ch)
    url: https://www.cgm19.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cgm 19 (Redirect to cgm19.parzival.digitaleditions.ch)
    url: https://www.cgm19.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod AA91
    url: https://codaa91.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod AA91 (Redirect to codaa91.parzival.unibe.ch)
    url: https://codaa91.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod AA91 (Redirect to codaa91.parzival.unibe.ch)
    url: https://www.codaa91.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod AA91 (Redirect to codaa91.parzival.digitaleditions.ch)
    url: https://www.codaa91.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod 857
    url: https://cod857.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod 857 (Redirect to cod857.parzival.unibe.ch)
    url: https://cod857.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod 857 (Redirect to cod857.parzival.unibe.ch)
    url: https://www.cod857.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Cod 857 (Redirect to cod857.parzival.digitaleditions.ch)
    url: https://www.cod857.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Schwerin
    url: https://schwerin.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Schwerin (Redirect to schwerin.parzival.unibe.ch)
    url: https://schwerin.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Schwerin (Redirect to schwerin.parzival.unibe.ch)
    url: https://www.schwerin.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Schwerin (Redirect to schwerin.parzival.digitaleditions.ch)
    url: https://www.schwerin.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Zürcher Skriptorium
    url: https://skriptoriumzh.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Zürcher Skriptorium (Redirect to skriptoriumzh.parzival.unibe.ch)
    url: https://skriptoriumzh.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Zürcher Skriptorium (Redirect to skriptoriumzh.parzival.unibe.ch)
    url: https://www.skriptoriumzh.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival – Zürcher Skriptorium (Redirect to skriptoriumzh.parzival.digitaleditions.ch)
    url: https://www.skriptoriumzh.parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: RdL – hallerNet (data)
    url: https://data.hallernet.org/
    expectedStatusCodes:
      - 401
  - name: RdL – hallernet.org (Redirect to "République des Lettres")
    url: https://hallernet.org/
    expectedStatusCodes:
      - 200
  - name: RdL – md.hallernet.org (Redirect to "République des Lettres (CodiMD)")
    url: https://md.hallernet.org/
    expectedStatusCodes:
      - 200
  - name: RdL – République des Lettres (CodiMD)
    url: https://md.republique-des-lettres.ch/
    expectedStatusCodes:
      - 200
  - name: RdL – République des Lettres - Daten- und Editionsplattform
    url: https://republique-des-lettres.ch/
    expectedStatusCodes:
      - 200
  - name: ReSED – Re-use of editions and text collections
    url: https://workshop.resed.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber
    url: https://wellcome-schreiber.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber (Redirect to wellcome-schreiber.unibe.ch)
    url: https://wellcome-schreiber.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber (Redirect to wellcome-schreiber.unibe.ch)
    url: https://www.wellcome-schreiber.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber (Redirect to wellcome-schreiber.digitaleditions.ch)
    url: https://www.wellcome-schreiber.unibe.ch/
    expectedStatusCodes:
      - 200

status-website:
  logoUrl: https://www.unibe.ch/media/media_global/logo_unibe_3z_120.svg
  themeUrl: https://status.digitaleditions.ch/custom_theme.css
  name: DH Services Monitoring
  cname: status.digitaleditions.ch
  introTitle: "Service Status Dashboard"
  introMessage: |
    This dashboard monitors the availability and performance of digital humanities services at the University of Bern.
    
    **Monitored Services:**
    - Digital edition platforms and APIs
    - Research project websites
    - Data visualization and collaboration tools
    
    For support or to report issues, please contact the Digital Humanities team. For more information, see [here](https://github.com/DHBern/upptime_digitaleditions/blob/master/DETAILS.md).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: DHBern
      href: https://dh.unibe.ch/
