owner: DHBern
repo: upptime_digitaleditions

sites:
  - name: Digital Editions - University of Bern
    url: https://digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Brandans Meerfahrt
    url: https://brandans-meerfahrt.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Re-use of editions and text collections
    url: https://workshop.resed.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek
    url: https://gossembrot.unibe.ch/gossembrot-portal/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber (Redirect to wellcome-schreiber.unibe.ch)
    url: https://wellcome-schreiber.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Wellcome Schreiber
    url: https://wellcome-schreiber.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival-Projekt
    url: https://parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival API
    url: https://data.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Arcipelago Ceresa
    url: https://arcipelago-ceresa.digitaleditions.ch/
    expectedStatusCodes:
      - 404
  - name: Arcipelago Ceresa IIIF presentation API
    url: https://iiif.arcipelago-ceresa.digitaleditions.ch/presentation/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach. Digitale Edition der Kleinen Formen und Briefe
    url: https://annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach DAV
    url: https://dav.annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 401
  - name: hallerNet (data)
    url: https://data.hallernet.org/
    expectedStatusCodes:
      - 401
  - name: hallernet.org (Redirect to "République des Lettres")
    url: https://hallernet.org/
    expectedStatusCodes:
      - 200
  - name: md.hallernet.org (Redirect to "République des Lettres (CodiMD)")
    url: https://md.hallernet.org/
    expectedStatusCodes:
      - 200
  - name: République des Lettres (CodiMD)
    url: https://md.republique-des-lettres.ch/
    expectedStatusCodes:
      - 200
  - name: République des Lettres - Daten- und Editionsplattform
    url: https://republique-des-lettres.ch/
    expectedStatusCodes:
      - 200

status-website:
  logoUrl: https://www.unibe.ch/media/media_global/logo_unibe_3z_120.svg
  themeUrl: https://status.digitaleditions.ch/custom_theme.css
  name: DH Services Monitoring
  cname: status.digitaleditions.ch
  introTitle: "Service Status Dashboard"
  introMessage: |
    This dashboard monitors the availability and performance of digital humanities services at the University of Bern.
    
    **Monitored Services:**
    - Digital edition platforms and APIs
    - Research project websites
    - Data visualization and collaboration tools
    
    For support or to report issues, please contact the Digital Humanities team. For more information, see [belo](#detailed_information_custom)
  customFootHtml: |
    <h1 id="detailed_information_custom">Details</h1>
    <h2>What is being checked?</h2>
    <p>The monitoring checks at regular intervals (currently every 15 minutes) whether a server responds at a specific web address (URL). For each monitored address, a status code is defined that is considered normal.</p>

    <p>The monitoring is considered “in order” if exactly the expected status code is returned. In this case, **UP** is displayed. As soon as an unexpected status code is returned or the connection has failed, **DOWN** is displayed.</p>

    <p><i>Response time</i>: The monitoring measures how long the server takes to respond. This serves only as an indication of potential technical problems, not as a performance benchmark.</p>

    <h2>What is explicitly not being checked?</h2>
    <p>The monitoring does not check:</p>
    <ol>
    <li> Website content: The monitoring does not check, whether texts, metadata or images, transcriptions and comments are displayed correctly and complete. It does not check, whether the “correct” page is being delivered. A page may be technically accessible (status “OK”) even if content is missing or incorrect.</li>
    <li>Functionality of web applications: The monitoring does not behave like a human user and performs no interactions. Search or filter functions, viewers, etc., are not checked.</li>
    <li>Subject-specific or semantic correctness: Only whether the service responds is checked, not what it delivers in terms of content.</li>
    <li>Display in the browser: The monitoring does not use a web browser. A page may be “UP” even if it appears faulty in a browser.</li>

    <h2>Monitoring service from the Universitiy Library of Bern</h2>

    <p>Initially, this service was established as part of a service of the University Library Bern (LINK to be added soon) for research projects with digital editions. However, it is also used for additional technical services and websites.</p>

    <p>For websites for which research projects have a contractual agreement with the University Library (visually marked, tbd), a notification is sent to the University Library (Open Science, Research Data Management) if an unexpected status code occurs.</p>

    <p>Part of this agreement is that, in the event of a problem and after consultation with the Data Science Lab, the University Library will contact the project management and/or the responsible institute management if a resolution is necessary.</p>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: DHBern
      href: https://www.dh.unibe.ch/
