owner: DHBern
repo: upptime_digitaleditions

sites:
  - name: Digital Editions - University of Bern
    url: https://digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Brandans Meerfahrt
    url: https://brandans-meerfahrt.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Re-use of editions and text collections
    url: https://workshop.resed.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek
    url: https://gossembrot.unibe.ch/gossembrot-portal/
    expectedStatusCodes:
      - 200
  - name: Parzival-Projekt
    url: https://parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Parzival API
    url: https://data.parzival.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Arcipelago Ceresa
    url: https://arcipelago-ceresa.digitaleditions.ch/
    expectedStatusCodes:
      - 404
  - name: Arcipelago Ceresa IIIF presentation API
    url: https://iiif.arcipelago-ceresa.digitaleditions.ch/presentation/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach. Digitale Edition der Kleinen Formen und Briefe
    url: https://annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach DAV
    url: https://dav.annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 401
  - name: hallerNet (data)
    url: https://data.hallernet.org/
    expectedStatusCodes:
      - 401
  - name: hallernet.org (Redirect to "République des Lettres")
    url: https://hallernet.org/
    expectedStatusCodes:
      - 200
  - name: md.hallernet.org (Redirect to "République des Lettres (CodiMD)")
    url: https://md.hallernet.org/
    expectedStatusCodes:
      - 200
  - name: République des Lettres (CodiMD)
    url: https://md.republique-des-lettres.ch/
    expectedStatusCodes:
      - 200
  - name: République des Lettres - Daten- und Editionsplattform
    url: https://republique-des-lettres.ch/
    expectedStatusCodes:
      - 200

status-website:
  logoUrl: https://www.unibe.ch/media/media_global/logo_unibe_3z_120.svg
  themeUrl: https://status.digitaleditions.ch/custom_theme.css
  name: DH Services Monitoring
  cname: status.digitaleditions.ch
  introTitle: "Service Status Dashboard"
  introMessage: |
    This dashboard monitors the availability and performance of digital humanities services at the University of Bern.
    
    **Monitored Services:**
    - Digital edition platforms and APIs
    - Research project websites
    - Data visualization and collaboration tools
    
    For support or to report issues, please contact the Digital Humanities team.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: DHBern
      href: https://www.dh.unibe.ch/