owner: DHBern
repo: upptime_digitaleditions

sites:
  - name: Digital Editions - University of Bern
    url: https://digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Brandans Meerfahrt
    url: https://brandans-meerfahrt.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Re-use of editions and text collections
    url: https://workshop.resed.digitaleditions.ch/
    expectedStatusCodes:
      - 200
  - name: Gossembrot Bibliothek
    url: https://gossembrot.unibe.ch/gossembrot-portal/
    expectedStatusCodes:
      - 200
  - name: Parzival-Projekt
    url: https://parzival.unibe.ch/
    expectedStatusCodes:
      - 200
  - name: Arcipelago Ceresa
    url: https://arcipelago-ceresa.digitaleditions.ch/
    expectedStatusCodes:
      - 404
  - name: Arcipelago Ceresa IIIF presentation API
    url: https://iiif.arcipelago-ceresa.digitaleditions.ch/presentation/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach. Digitale Edition der Kleinen Formen und Briefe
    url: https://annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 200
  - name: Annemarie Schwarzenbach DAV
    url: https://dav.annemarie-schwarzenbach.ch/
    expectedStatusCodes:
      - 401
  - name: hallerNet (data)
    url: https://data.hallernet.org/
    expectedStatusCodes:
      - 401
  - name: hallernet.org (Redirect to "République des Lettres")
    url: https://hallernet.org/
    expectedStatusCodes:
      - 200
  - name: md.hallernet.org (Redirect to "République des Lettres (CodiMD)")
    url: https://md.hallernet.org/
    expectedStatusCodes:
      - 200
  - name: République des Lettres (CodiMD)
    url: https://md.republique-des-lettres.ch/
    expectedStatusCodes:
      - 200
  - name: République des Lettres - Daten- und Editionsplattform
    url: https://republique-des-lettres.ch/
    expectedStatusCodes:
      - 200

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://status.digitaleditions.ch/custom_theme.css
  name: DH Services Monitoring (Demo)
  cname: status.digitaleditions.ch
  introTitle: "**Upptime** instance for DHBern"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
