owner: DHBern
repo: upptime_demo

sites:
  - name: Digital Editions - University of Bern
    url: https://digitaleditions.ch/
  - name: Brandans Meerfahrt
    url: https://brandans-meerfahrt.digitaleditions.ch/
  - name: Re-use of editions and text collections
    url: https://workshop.resed.digitaleditions.ch/

status-website:
  baseUrl: /upptime_demo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DH Services Monitoring (Demo)
  introTitle: "**Upptime** instance for DHBern"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
