# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Digital Editions - University of Bern
    url: https://digitaleditions.ch/
  - name: Wikipedia
    url: Brandans Meerfahrt | Brandans Meerfahrt
  - name: Hacker News
    url: https://workshop.resed.digitaleditions.ch/
  - name: Re-use of editions and text collections
    url: https://thissitedoesnotexist.koj.co

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DH Services Monitoring (Demo)
  introTitle: "**Upptime** instance for DHBern"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
